title: RCP Lab
description: Behavior as Resource-rational Adaptive INference
url: ""
baseurl: "/rcplab"

markdown: kramdown
permalink: pretty

logo: /assets/img/lab-logo-cropped.png

collections:
  posts:
    output: true

nav:
  - title: People
    url: /people/
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: Resources
    url: /resources/
  - title: News
    url: /news/

exclude:
  - README.md
  - resources/Research_statement_iitgn.pdf
  - resources/AI_CG_Course_Proposal_Sabya.pdf
